<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A .NET library implementing Komair.Expressions.Mapping using the Mapster package.</Description>
    <PackageTags>$(KomairPackageTags);mapster;expressions;expression-trees;mapping</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Komair.Expressions.Mapping\Komair.Expressions.Mapping.csproj" />
  </ItemGroup>

</Project>
