<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>A .NET library implementing Komair.Expressions.Serialization using the System.Text.Json APIs.</Description>
    <PackageTags>$(KomairPackageTags);json;system-text-json;serialization;expressions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Komair.Expressions.Serialization\Komair.Expressions.Serialization.csproj" />
  </ItemGroup>

</Project>
