<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A .NET abstraction library for serializing Komair.Expressions.ExpressionNode objects to/from other types (in particular, System.Linq.Expressions objects).</Description>
    <PackageTags>$(KomairPackageTags);expressions;serialization;expression-trees</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Komair.Expressions\Komair.Expressions.csproj" />
  </ItemGroup>

</Project>
